FROM eclipse-temurin:21-jre-jammy
RUN apt-get update && apt-get install -y docker.io
WORKDIR /app
ARG MODULE_NAME
COPY ${MODULE_NAME}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]