server.port=8086
spring.application.name=supervisor-service

# --- Spring AI (Gemini using OpenAI-compatible API wrapper) ---
#spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com/v1beta/openai
#spring.ai.openai.chat.completions-path=/chat/completions
#spring.ai.openai.chat.options.model=gemini-2.5-pro
#spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
#spring.ai.ollama.chat.model=llama3.1

# --- MCP Sync Client ---
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.request-timeout=60s
spring.ai.mcp.client.sse.connections.metric-agent.url=http://localhost:5173
spring.ai.mcp.client.sse.connections.logs-agent.url=http://localhost:5174
spring.ai.mcp.client.sse.connections.anomaly-agent.url=http://localhost:5175
spring.ai.mcp.client.sse.connections.heal-agent.url=http://localhost:5176
logging.level.org.springframework.ai.mcp=DEBUG
logging.level.org.springframework.beans=DEBUG
